# Generated by Django 4.0.5 on 2022-06-18 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.CharField(blank=True, max_length=255, null=True)),
                ('phone', models.CharField(blank=True, max_length=255, null=True)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('type', models.CharField(blank=True, choices=[('scientist', 'SCIENTIST'), ('engineer', 'ENGINEER'), ('phisic', 'PHYSIC')], default='engineer', max_length=255, null=True)),
            ],
        ),
    ]
